#!/bin/bash
echo "14" > /sys/class/gpio/export
echot "out" > /sys/class/gpio/gpio14/direction
echo "1" > /sys/class/gpio/gpio14/value
sleep 5
echo "0" > /sys/class/gpio/gpio14/value
sleep 1
echo "0" >  /sys/class/gpio/gpio14/value
